  - name: Set up a web server
    hosts: webservers
    become: true
    
    tasks:
      - name: Check apache is installed
        apt:
          name: apache2
          state: present

      - name: Check Apache is running
        service:
          name: apache2
          state: started
          enabled: true

      - name: Create a custom index.html
        template:
          src: /Users/AnanyaShetty/terraform-ansible-setup/index.html.j2
          dest: /var/www/html/index.html
          mode: 0644

      - name: Create a custom index.html file
        template:
         src: /Users/AnanyaShetty/terraform-ansible-setup/index.html.j2
         dest: /var/www/html/index.html
         mode: 0644
